base_url: http://localhost:3000
terrain_url: http://terrain
listen_port: 3000
user_portal_url: https://portaldev.cyverse.org
legacy_de_url: https://legacy-qa.cyverse.org

logging:
    level: info
    label: sonora server

db:
    host: localhost
    port: 5432
    user: null
    password: null
    database: de

sessions:
    secret: "keyboard cat"
    secure_cookie: false
    ttl: 8
    poll_interval_ms: 5000

keycloak:
    server_url: "https://kc.cyverse.org/auth"
    realm: "CyVerse"
    client_id: null
    client_secret: null

intercom:
    app_id: appId
    enabled: true
    company_id: DE-DEV
    company_name: DISCOVERY ENVIRONMENT
    user_profile_url: https://app.intercom.com/apps/appId/users/show?user_id=

admin:
    groups: some-group
    group_attribute_name: entitlement

analysis:
    support:
        user: siuser
        source_id: ldap

irods:
    home_path: /iplant/home
    trash_path: /iplant/trash/home
    community_path: /iplant/home/shared
    web_dav:
        anon_uri: https://data.cyverse.org/dav-anon  

fileIdentifier:
    htPathList: "# application/vnd.de.path-list+csv; version=1"
    multiInputPathList: "# application/vnd.de.multi-input-path-list+csv; version=1"

analytics:
    enabled: false
    id: ga-id

vice:
    defaultImage: discoenv/cas-proxy
    defaultName: cas-proxy
    defaultCasUrl: https://olson.cyverse.org/cas
    defaultCasValidate: validate
    concurrentJobs: 2
    useCaseCharsMin: 60
    initContainerName: input-files-init
    inputFilesContainerName: input-files
    viceProxyContainerName: vice-proxy
    analysisContainerName: analysis
    deploymentTimeoutMs: 180000

services:
    ontology_lookup_service:
        base: https://www.ebi.ac.uk/ols/api/select
    unified_astronomy_thesaurus:
        base: https://vocabs.ands.org.au/repository/api/lda/aas/the-unified-astronomy-thesaurus/current/concept.json

grouper:
    allUsers: GrouperAll
    admin: de_grouper

unleash:
    api_url: http://unleash:4242/api
    client_secret: null
    maintenance_flag: DE-Maintenance

username:
    suffix: iplantcollaborative.org

subscriptions:
    checkout_url: https://cyverse-subscription-sandbox.phoenixbioinformatics.org
    enforce: true
